scoreboard:
  title: "<gold><bold>BRAWL <red>[Beta]"
  url: "<yellow>minebo.net"

mongo:
  uri: "mongodb://localhost:27017"
  database: "Brawl"

manage:
  freekitsmode: false

extra-money:
  owner: 50