name: Brawl
version: '1.0-DEV'
description: "The main plugin for Brawl, a kit based pvp gamemode on Minebo."
authors: ["Ian Rich"]
website: "https://github.com/MineboMC/Brawl"
main: net.minebo.brawl.Brawl
soft-depend: ["kRegions"]
api-version: '1.20'
